run:
  skip-dirs:
    - test-cmds
  timeout: 5m

linters:
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - paralleltest
    - sqlclosecheck
    - staticcheck
    - structcheck
    - unconvert
    - unused
    - varcheck

linters-settings:
  errcheck:
    ignore: github.com/go-kit/kit/log:Log
  gofmt:
    simplify: false

issues:
  exclude-rules:
    # False positive: https://github.com/kunwardeep/paralleltest/issues/8.
    - linters:
      - paralleltest
      text: "does not use range value in test Run"