version: "2"
linters:
  enable:
    - bodyclose
    - gosec
    - misspell
    - nakedret
    - noctx
    - paralleltest
    - sqlclosecheck
    - unconvert
  settings:
    errcheck:
      exclude-functions:
        - github.com/go-kit/kit/log:Log
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - paralleltest
        text: does not use range value in test Run
    paths:
      - test-cmds
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
    paths:
      - test-cmds
      - third_party$
      - builtin$
      - examples$
