name: actionlint

# See https://github.com/rhysd/actionlint

on:
  pull_request:
    branches:
      - main

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Go 1.x
        uses: actions/setup-go@v7
        with:
          go-version: 1.24
      - name: install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@393031adb9afb225ee52ae2ccd7a5af5525e03e8 # v1.7.11
      - name: actionlint
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          actionlint -color -ignore SC2046
