name: Cross Language Tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Go ${{ matrix.go }} Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        go:
          - '1.16'
          - '1.18'
        ruby:
          - '3.1.2'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
        cache: true
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Cross Language Tests
      env:
        GO111MODULE: on
      run: go test ./cross_language_tests/...